### ISSUE TITLE
magit 2 compat

### ISSUE THREAD

**Issue by mjhoy** [emacsattic/org-magit#7]
for anyone else who doesn't want to switch to orgit (it uses different syntax and existing links no longer work), you can continue to save magit commit links by adjusting the expression

`(org-magit-check-mode magit-commit-mode)`

to

```
(or (org-magit-check-mode magit-commit-mode)
     (org-magit-check-mode magit-revision-mode))
```

my tweak [lives here][tweak].

[tweak]:https://github.com/mjhoy/dotfiles/blob/master/emacs.d/site-lisp/org-magit.el

**Comment by tarsius** [comment]
Please open a pr. I don't really maintain this package, but am fine with clicking on "merge" :-)

**Comment by tarsius** [comment]
Did not see your offer to maintain this before I wrote the above.

**Comment by mjhoy** [comment]
sorry, assumed you weren't accepting patches anymore. can send one in.

**Comment by tarsius** [comment]
Well, I didn't intend to - but if this can be fixed so easily, then there's no good reason not to do it.

**Comment by tarsius** [comment]
@sigma Are you interested in maintaining this again? Otherwise I am going to hand it over to @mjhoy.

**Comment by mjhoy** [comment]
just FYI i'm still fine to take over as maintainer. closing this issue now

**Comment by tarsius** [comment]
To make this official please clone this repository (libraries should live in their own repository, not in a users personal configuration repository), apply your changes, and add a "Maintainer" header keyword. I will then delete this repository and instead mirror yours on the Emacsmirror. You should also explain in the documentation why someone might prefer `org-magit` over `orgit`.

**Comment by mjhoy** [comment]
i was intending to maintain simply for the fact all my links use the old format and to continue to point new users to `orgit`. however perhaps a better solution is to develop something that will translate all `org-magit` links into `orgit` ?

**Comment by tarsius** [comment]
Well then, lets keep it simple. Please send me a pr against this repository. That should do it.

> however perhaps a better solution is to develop something that will translate all `org-magit` links into `orgit` ?

That would probably be best, but likely also quite a bit of work.

**Comment by mjhoy** [comment]
i just realized i had already _made_ the PR i wanted, and you accepted, way back when. whoops, sorry for the confusion!

I will look into translating links from `org-magit` -> `orgit`. If I can come up with a solution i'll write a README file for this repository with instructions, perhaps, and send a PR. thanks.
